version: "3.7"
services:
  db:
    image: postgres:12.4
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - "5432:5432"
volumes:
  postgresql_data:
